// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;

import frc.robot.Robot;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpiutil.math.VecBuilder;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import com.ctre.phoenix.motorcontrol.ControlMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
    import com.ctre.phoenix.motorcontrol.*;

/**
 *
 */
public class FlyWheel extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_VictorSPX flyWheelVictor;
private WPI_TalonSRX flyWheelTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public FlyWheel() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
flyWheelVictor = new WPI_VictorSPX(15);


        
flyWheelTalon = new WPI_TalonSRX(19);


        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        flyWheelVictor.setInverted(true);
        flyWheelVictor.follow(flyWheelTalon);
        configurePID(flyWheelTalon);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem

    public void stop() {
        flyWheelTalon.stopMotor();
    }

    public void move(double speed) {
        flyWheelTalon.set(ControlMode.PercentOutput, speed);
    }

    public void velocityMove(double velocity) {
        flyWheelTalon.set(ControlMode.Velocity, velocity);
    }

    public boolean isFlywheelAtSpeed(double velocity) {
        if (flyWheelTalon.getSelectedSensorVelocity() == velocity) return true;
        else return false;
    }

    private void configurePID(WPI_TalonSRX _talon) {
        /**
        * Which PID slot to pull gains from. Starting 2018, you can choose from
        * 0,1,2 or 3. Only the first two (0,1) are visible in web-based
        * configuration.
        */
       final int kSlotIdx = 0;

       /**
        * Talon SRX/ Victor SPX will supported multiple (cascaded) PID loops. For
        * now we just want the primary one.
        */
       final int kPIDLoopIdx = 0;

       /**
        * Set to zero to skip waiting for confirmation, set to nonzero to wait and
        * report to DS if action fails.
        */
       final int kTimeoutMs = 30;

       /**
        * PID Gains may have to be adjusted based on the responsiveness of control loop.
        * kF: 1023 represents output value to Talon at 100%, 7200 represents Velocity units at 100% output
        * 
        * 	                                    			  kP   kI   kD   kF          Iz    PeakOut */
       final double kP = 0.25;
       final double kI = 0.001;
       final double kD = 20;
       final double kF = 1023/7200;
       final int kIzone = 300;
       final double kPeakOutput = 1.00;

       /* Factory Default all hardware to prevent unexpected behaviour */
       _talon.configFactoryDefault();

       /* Config sensor used for Primary PID [Velocity] */
       _talon.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative,
                                           kPIDLoopIdx, 
                                           kTimeoutMs);
       
       /* Config the peak and nominal outputs */
       _talon.configNominalOutputForward(0, kTimeoutMs);
       _talon.configNominalOutputReverse(0, kTimeoutMs);
       _talon.configPeakOutputForward(1, kTimeoutMs);
       _talon.configPeakOutputReverse(-1, kTimeoutMs);
       
       /* Config the Velocity closed loop gains in slot0 */
       _talon.config_kF(kPIDLoopIdx, kF, kTimeoutMs);
       _talon.config_kP(kPIDLoopIdx, kP, kTimeoutMs);
       _talon.config_kI(kPIDLoopIdx, kI, kTimeoutMs);
       _talon.config_kD(kPIDLoopIdx, kD, kTimeoutMs);
       
   }

    // here. Call these from Commands.
   
}

