// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.Robot;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.networktables.NetworkTableEntry;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// ***** 5053 *****
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;

/**
 *
 */
public class RobotSensors extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PowerDistributionPanel powerPanel;
private AnalogGyro frcGyroAccel;
private Ultrasonic bottomUltrasonic;
private Ultrasonic readyToLoadUltrasonic;
private Ultrasonic topUltrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // ***** 5053 *****
    NetworkTable table;
    NetworkTableEntry tx;
    NetworkTableEntry ty;
    NetworkTableEntry ta;
    NetworkTableEntry tv;
    int INTAKE_STATE;
    int kInRange = 0;
    int kIncreasing = 1;
    int kEmpty = 2;
    int kDecreasing = 3;

    
    public RobotSensors() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
powerPanel = new PowerDistributionPanel(0);
addChild("powerPanel",powerPanel);

        
frcGyroAccel = new AnalogGyro(0);
addChild("frcGyroAccel",frcGyroAccel);
frcGyroAccel.setSensitivity(0.007);
        
bottomUltrasonic = new Ultrasonic(2, 3);
addChild("BottomUltrasonic",bottomUltrasonic);

        
readyToLoadUltrasonic = new Ultrasonic(4, 5);
addChild("ReadyToLoadUltrasonic",readyToLoadUltrasonic);

        
topUltrasonic = new Ultrasonic(0, 1);
addChild("TopUltrasonic",topUltrasonic);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    // ***** 5053 *****
    table = NetworkTableInstance.getDefault().getTable("limelight");
    tx = table.getEntry("tx");
    ty = table.getEntry("ty");
    ta = table.getEntry("ta");
    tv = table.getEntry("tv");

    readyToLoadUltrasonic.setEnabled(true);
    readyToLoadUltrasonic.setAutomaticMode(true);
    bottomUltrasonic.setEnabled(true);
    bottomUltrasonic.setAutomaticMode(true);
    topUltrasonic.setEnabled(true);
    topUltrasonic.setAutomaticMode(true);
    
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        Robot.oi.updateVisionTA(ta.getDouble(0));
        Robot.oi.updateVisionTX(tx.getDouble(0));
        Robot.oi.updateVisionTY(ty.getDouble(0));
        Robot.oi.updateVisionTV(tv.getBoolean(false));
        Robot.oi.updateReadyToLoadSensor(readyToLoadUltrasonic.getRangeInches());
        Robot.oi.updateBottomSensor(bottomUltrasonic.getRangeInches());
        Robot.oi.updateTopSensor(topUltrasonic.getRangeInches());


    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.



}

